// TypeScript mirrors of the Rust types sent across the Tauri boundary. One place for the whole
// contract — keep these in sync with `src-tauri/src/.../bootstrap.rs`, `inspect.rs` and the
// command signatures in `lib.rs`. (Longer term these could be generated by tauri-specta/ts-rs.)

export type GameVersion = "Kanto" | "Hoenn";
export interface GameConfig {
  dir: string;
  version: GameVersion;
}

// --- bootstrap (loaded once per game, populates the filter controls) ---

export interface NamedId {
  id: number;
  name: string;
}
export interface MoveOption {
  id: number;
  name: string;
  // type id; resolve its name/icon via the types table
  ty: number;
  category: 0 | 1 | 2;
  power: number | null;
  effect_chance: number | null;
  // null = never misses
  accuracy: number | null;
  priority: number;
  description: string;
  flags: string;
}

export interface MoveFlags {
  contact: boolean;
  sound: boolean;
  pulse: boolean;
  bomb: boolean;
  biting: boolean;
  punching: boolean;
  dance: boolean;
  high_crit_rate: boolean;
}

export interface SpeciesOption {
  id: number;
  dex_id: number;
  name: string;
}
export interface Range {
  min: number;
  max: number;
}
export interface StatBounds {
  hp: Range;
  atk: Range;
  def: Range;
  spa: Range;
  spd: Range;
  spe: Range;
  bst: Range;
}
export interface Bootstrap {
  species_count: number;
  species: SpeciesOption[];
  moves: MoveOption[];
  types: NamedId[];
  abilities: NamedId[];
  stat_bounds: StatBounds;
  // slider bounds for the move-list power / secondary-effect-chance / accuracy / priority filters
  move_power: Range;
  move_effect_chance: Range;
  move_accuracy: Range;
  move_priority: Range;
  block_ids_above: number | null;
}

// `search` returns bare fusion ids; the grid hydrates the on-screen ones into FusionCards via the
// `fusion_cards` command (name + type ids, both decided backend-side). Keyed by id so async
// results match back to the right cell after scrolling.
export interface FusionCard {
  id: number;
  name: string;
  types: number[];
}

// --- inspect (rich detail for one fusion) ---

export interface ComponentBrief {
  index: number;
  dex_id: number;
  name: string;
}
// no label — the front end knows the 7 stats by position (HP, ATK, DEF, SP.ATK, SP.DEF, SPEED, TOTAL)
export interface StatRow {
  value: number;
  head: number;
  body: number;
}
export interface NamedDesc {
  name: string;
  description: string;
}
export interface Matchup {
  // effectiveness in quarters (0, 1=¼×, 2=½×, 8=2×, 16=4×); the front end renders the glyph
  multiplier: number;
  types: number[];
}
export interface EncounterRow {
  location: string;
  // raw EncounterMethod variant name (e.g. "Land", "WaterNight"); mapped to a label client-side
  method: string;
  chance: number;
  min_level: number;
  max_level: number;
  mode: "Classic" | "Remix" | "Both";
}

// One Pokémon found at a location
// Returned by the `area_encounters` command
export interface AreaEncounter {
  species: number;
  dex_id: number;
  name: string;
  types: [number, number | null];
  method: string;
  chance: number;
  min_level: number;
  max_level: number;
  mode: "Classic" | "Remix" | "Both";
}

// The TM/HM that teaches a move, plus where to find it.
export interface MachineSource {
  // the machine's in-game name, e.g. "TM35"
  name: string;
  is_hm: boolean;
  // routes the machine is found on; empty = mart/event-only
  locations: string[];
}

// A Move Expert signature move: which expert teaches it, where, and the eligibility rule.
export interface ExpertSource {
  // taught by the Legendary Move Expert rather than the regular one
  legendary: boolean;
  // routes the relevant Move Expert NPC is found on
  locations: string[];
  // plain-English eligibility (the move's separate rules joined by "or")
  condition: string;
}

// The move hover-card: a move's stats plus its TM/HM, tutor, and Move Expert sources.
// Returned by the `move_card` command (send `{ moveId: number }`).
export interface MoveCard {
  name: string;
  // type id; resolve its name/icon via the types table
  ty: number;
  category: 0 | 1 | 2;
  power: number | null;
  // null = never misses
  accuracy: number | null;
  pp: number;
  priority: number;
  effect_chance: number | null;
  description: string;
  // compact flag string; decode against MOVE_FLAGS
  flags: string;
  // present iff a TM/HM teaches this move
  machine: MachineSource | null;
  // routes where a move tutor teaches this move; empty if none
  tutor_locations: string[];
  // present iff this is a Move Expert signature move
  expert: ExpertSource | null;
}

export type LevelNote =
  | "none"
  | "day"
  | "night"
  | "atk_gt_def"
  | "atk_lt_def"
  | "atk_eq_def";

// how a fusion neighbour is reached; item/move ids are already resolved to names backend-side
export type EvoCondition =
  | { kind: "level"; level: number; note: LevelNote }
  | { kind: "use_item"; item: string }
  | { kind: "hold_day"; item: string }
  | { kind: "trade"; item: string }
  | { kind: "know_move"; name: string };

// how a move is learned, merged across both parents; the front end renders the chips
export interface LearnSources {
  level: number | null;
  machine: string | null;
  tutor: boolean;
  egg: boolean;
  // Move Expert signature move: true = legendary expert, false = regular, null = not an expert move
  expert: boolean | null;
}
export interface EvoNode {
  dex_id: number;
  name: string;
  // (primary, optional secondary) type ids
  types: [number, number | null];
  from_condition: EvoCondition | null;
  encounters: EncounterRow[];
}
export interface FusionEvo {
  head: number;
  body: number;
  head_dex: number;
  body_dex: number;
  name: string;
  via: "Head" | "Body";
  condition: EvoCondition | null;
}
export interface MoveRow {
  id: number;
  name: string;
  ty: number;
  category: 0 | 1 | 2;
  power: number | null;
  accuracy: number | null;
  pp: number;
  description: string;
  sources: LearnSources;
}
export interface SpriteVariant {
  variant: string;
  artist: string | null;
}
export interface FusionDetail {
  head: ComponentBrief;
  body: ComponentBrief;
  fusion_name: string;
  // (primary, optional secondary) type ids
  types: [number, number | null];
  stats: StatRow[];
  regular_abilities: NamedDesc[];
  hidden_abilities: NamedDesc[];
  matchups: Matchup[];
  evolves_from: FusionEvo[];
  evolves_into: FusionEvo[];
  head_line: EvoNode[];
  body_line: EvoNode[];
  moves: MoveRow[];
  sprites: SpriteVariant[];
}

// --- shared constants that must match the backend ---

export const STATS = ["hp", "atk", "def", "spa", "spd", "spe", "bst"] as const;
export type StatKey = (typeof STATS)[number];

// matches the backend Metric enum (variant names), grouped into the categories the cascade sort menu shows
// The backend keeps one flat `Metric` enum so this grouping is purely presentation
export const METRIC_GROUPS = [
  {
    label: "Base stats",
    metrics: [
      { value: "Bst", label: "BST" },
      { value: "Hp", label: "HP" },
      { value: "Atk", label: "Attack" },
      { value: "Def", label: "Defense" },
      { value: "Spa", label: "Sp. Atk" },
      { value: "Spd", label: "Sp. Def" },
      { value: "Spe", label: "Speed" },
    ],
  },
  {
    label: "Synergy",
    metrics: [
      { value: "SumOfParts", label: "Sum of Parts" },
      { value: "SynergyRatio", label: "Synergy Ratio" },
      { value: "SurplusOverBest", label: "Surplus vs Best" },
      { value: "BalancedSynergy", label: "Balanced Synergy" },
    ],
  },
  {
    label: "Effective HP",
    metrics: [
      { value: "PhysicalEHp", label: "Physical eHP" },
      { value: "SpecialEHp", label: "Special eHP" },
      { value: "CombinedEHp", label: "Combined eHP" },
    ],
  },
  {
    label: "Type-adjusted eHP",
    metrics: [
      { value: "TAPhysicalEHp", label: "TA Physical eHP" },
      { value: "TASpecialEHp", label: "TA Special eHP" },
      { value: "TACombinedEHp", label: "TA Combined eHP" },
    ],
  },
  {
    label: "Sweep score",
    metrics: [
      { value: "PhysicalSweep", label: "Physical Sweep" },
      { value: "SpecialSweep", label: "Special Sweep" },
      { value: "CombinedSweep", label: "Combined Sweep" },
      { value: "MixedSweep", label: "Mixed Sweep" },
    ],
  },
  {
    label: "Type-adjusted Sweep",
    metrics: [
      { value: "TAPhysicalSweep", label: "TA Physical Sweep" },
      { value: "TASpecialSweep", label: "TA Special Sweep" },
      { value: "TACombinedSweep", label: "TA Combined Sweep" },
      { value: "TAMixedSweep", label: "TA Mixed Sweep" },
    ],
  },
] as const;

export type Metric = (typeof METRIC_GROUPS)[number]["metrics"][number]["value"];
export type MetricOption = { value: Metric; label: string };
export type MetricGroup = { label: string; metrics: readonly MetricOption[] };

// flat view + label lookup, for callers that don't care about grouping
export const METRICS: readonly MetricOption[] = METRIC_GROUPS.flatMap(
  (g) => g.metrics as readonly MetricOption[],
);
export function metricLabel(value: Metric): string {
  return METRICS.find((m) => m.value === value)?.label ?? value;
}

// the synergy metrics react to a per-stat include/exclude selection (the toolbar stat chips)
export const SYNERGY_METRICS: ReadonlySet<Metric> = new Set(
  METRIC_GROUPS.find((g) => g.label === "Synergy")!.metrics.map((m) => m.value),
);

// stats that can count toward synergy; `value` matches the backend `Stat` enum (lowercase)
export const SYNERGY_STATS = [
  { value: "hp", label: "HP" },
  { value: "atk", label: "Atk" },
  { value: "def", label: "Def" },
  { value: "spa", label: "SpA" },
  { value: "spd", label: "SpD" },
  { value: "spe", label: "Spe" },
] as const;
export type SynergyStat = (typeof SYNERGY_STATS)[number]["value"];

// matches the backend EvolutionFilter enum (variant names); null = no evolution constraint
export type EvolutionFilter = "CanEvolve" | "FullyEvolved";

// matches the backend CustomSpriteFilter enum (variant names); null = no sprite constraint.
// "Custom" keeps only fusions with a hand-drawn sprite, "Autogen" only those without one.
export type CustomSpriteFilter = "Custom" | "Autogen";

// ability-relevant move flags (must match the backend's ABILITY_MOVE_FLAGS labels)
export const MOVE_FLAGS = [
  ["Contact", "a"],
  ["Sound", "k"],
  ["Pulse", "m"],
  ["Bomb", "n"],
  ["Biting", "i"],
  ["Punching", "j"],
  ["Dance", "o"],
  ["High Crit", "h"],
] as const;

/// MOVE_CATEGORY[move_cat] will give the canonical name of a move's category
export const MOVE_CATEGORY = ["Physical", "Special", "Status"] as const;
