// TypeScript mirrors of the Rust types sent across the Tauri boundary. One place for the whole
// contract — keep these in sync with `src-tauri/src/.../bootstrap.rs`, `inspect.rs` and the
// command signatures in `lib.rs`. (Longer term these could be generated by tauri-specta/ts-rs.)

export type GameVersion = "Kanto" | "Hoenn";
export interface GameConfig {
  dir: string;
  version: GameVersion;
}

// --- bootstrap (loaded once per game, populates the filter controls) ---

export interface NamedId {
  id: number;
  name: string;
}
export interface MoveOption {
  id: number;
  name: string;
  // type id; resolve its name/icon via the types table
  ty: number;
  category: 0 | 1 | 2;
  power: number | null;
  description: string;
  flags: string;
}

export interface MoveFlags {
  contact: boolean;
  sound: boolean;
  pulse: boolean;
  bomb: boolean;
  biting: boolean;
  punching: boolean;
  dance: boolean;
  high_crit_rate: boolean;
}

export interface SpeciesOption {
  id: number;
  dex_id: number;
  name: string;
}
export interface Range {
  min: number;
  max: number;
}
export interface StatBounds {
  hp: Range;
  atk: Range;
  def: Range;
  spa: Range;
  spd: Range;
  spe: Range;
  bst: Range;
}
export interface Bootstrap {
  species_count: number;
  species: SpeciesOption[];
  moves: MoveOption[];
  types: NamedId[];
  abilities: NamedId[];
  stat_bounds: StatBounds;
  block_ids_above: number | null;
}

// `search` returns bare fusion ids; the grid hydrates the on-screen ones into FusionCards via the
// `fusion_cards` command (name + type ids, both decided backend-side). Keyed by id so async
// results match back to the right cell after scrolling.
export interface FusionCard {
  id: number;
  name: string;
  types: number[];
}

// --- inspect (rich detail for one fusion) ---

export interface ComponentBrief {
  index: number;
  dex_id: number;
  name: string;
}
// no label — the front end knows the 7 stats by position (HP, ATK, DEF, SP.ATK, SP.DEF, SPEED, TOTAL)
export interface StatRow {
  value: number;
  head: number;
  body: number;
}
export interface NamedDesc {
  name: string;
  description: string;
}
export interface Matchup {
  // effectiveness in quarters (0, 1=¼×, 2=½×, 8=2×, 16=4×); the front end renders the glyph
  multiplier: number;
  types: number[];
}
export interface EncounterRow {
  location: string;
  // raw EncounterMethod variant name (e.g. "Land", "WaterNight"); mapped to a label client-side
  method: string;
  chance: number;
  min_level: number;
  max_level: number;
  mode: "Classic" | "Remix" | "Both";
}

export type LevelNote =
  | "none"
  | "day"
  | "night"
  | "atk_gt_def"
  | "atk_lt_def"
  | "atk_eq_def";

// how a fusion neighbour is reached; item/move ids are already resolved to names backend-side
export type EvoCondition =
  | { kind: "level"; level: number; note: LevelNote }
  | { kind: "use_item"; item: string }
  | { kind: "hold_day"; item: string }
  | { kind: "trade"; item: string }
  | { kind: "know_move"; name: string };

// how a move is learned, merged across both parents; the front end renders the chips
export interface LearnSources {
  level: number | null;
  machine: string | null;
  tutor: boolean;
  egg: boolean;
}
export interface EvoNode {
  dex_id: number;
  name: string;
  // (primary, optional secondary) type ids
  types: [number, number | null];
  from_condition: EvoCondition | null;
  encounters: EncounterRow[];
}
export interface FusionEvo {
  head: number;
  body: number;
  head_dex: number;
  body_dex: number;
  name: string;
  via: "Head" | "Body";
  condition: EvoCondition | null;
}
export interface MoveRow {
  name: string;
  ty: number;
  category: 0 | 1 | 2;
  power: number | null;
  accuracy: number | null;
  pp: number;
  description: string;
  sources: LearnSources;
}
export interface SpriteVariant {
  variant: string;
  artist: string | null;
}
export interface FusionDetail {
  head: ComponentBrief;
  body: ComponentBrief;
  fusion_name: string;
  // (primary, optional secondary) type ids
  types: [number, number | null];
  stats: StatRow[];
  regular_abilities: NamedDesc[];
  hidden_abilities: NamedDesc[];
  matchups: Matchup[];
  evolves_from: FusionEvo[];
  evolves_into: FusionEvo[];
  head_line: EvoNode[];
  body_line: EvoNode[];
  moves: MoveRow[];
  sprites: SpriteVariant[];
}

// --- shared constants that must match the backend ---

export const STATS = ["hp", "atk", "def", "spa", "spd", "spe", "bst"] as const;
export type StatKey = (typeof STATS)[number];

// matches the backend SortBy enum (variant names)
export const SORTS = [
  { value: "DexNumber", label: "Dex order" },
  { value: "Bst", label: "BST" },
  { value: "Hp", label: "HP" },
  { value: "Atk", label: "Attack" },
  { value: "Def", label: "Defense" },
  { value: "Spa", label: "Sp. Atk" },
  { value: "Spd", label: "Sp. Def" },
  { value: "Spe", label: "Speed" },
] as const;
export type SortBy = (typeof SORTS)[number]["value"];

// ability-relevant move flags (must match the backend's ABILITY_MOVE_FLAGS labels)
export const MOVE_FLAGS = [
  ["Contact", "a"],
  ["Sound", "k"],
  ["Pulse", "m"],
  ["Bomb", "n"],
  ["Biting", "i"],
  ["Punching", "j"],
  ["Dance", "o"],
  ["High Crit", "h"],
] as const;

/// MOVE_CATEGORY[move_cat] will give the canonical name of a move's category
export const MOVE_CATEGORY = ["Physical", "Special", "Status"] as const;
